// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt88l24f42Ul2mViaoD-NcvCSDOCTS53A',
    appId: '1:500405287580:web:6c1c04ed8d1fa0d060cb59',
    messagingSenderId: '500405287580',
    projectId: 'my-easytravel',
    authDomain: 'my-easytravel.firebaseapp.com',
    storageBucket: 'my-easytravel.firebasestorage.app',
    measurementId: 'G-MZTNCQKV0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrfbk4-wuaKRYfNf23lGxlIiYjeG4Hd_w',
    appId: '1:500405287580:android:7813504ad6270f0d60cb59',
    messagingSenderId: '500405287580',
    projectId: 'my-easytravel',
    storageBucket: 'my-easytravel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIox47ztolOjhQZgY2toej9noqtc2uxHA',
    appId: '1:500405287580:ios:9bdca5815b21dbc760cb59',
    messagingSenderId: '500405287580',
    projectId: 'my-easytravel',
    storageBucket: 'my-easytravel.firebasestorage.app',
    iosBundleId: 'com.example.easyTravel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIox47ztolOjhQZgY2toej9noqtc2uxHA',
    appId: '1:500405287580:ios:9bdca5815b21dbc760cb59',
    messagingSenderId: '500405287580',
    projectId: 'my-easytravel',
    storageBucket: 'my-easytravel.firebasestorage.app',
    iosBundleId: 'com.example.easyTravel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDt88l24f42Ul2mViaoD-NcvCSDOCTS53A',
    appId: '1:500405287580:web:d83311f38670d5ae60cb59',
    messagingSenderId: '500405287580',
    projectId: 'my-easytravel',
    authDomain: 'my-easytravel.firebaseapp.com',
    storageBucket: 'my-easytravel.firebasestorage.app',
    measurementId: 'G-XG1NVPBERV',
  );
}
